# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: J Sean
description: 'J Seans Last Ride'
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://localhost:4000/" # the base hostname & protocol for your site, e.g. http://example.com

logo:
  logo: 'img/logo/logo.png'
  light: 'img/logo/light.png'
  mobile: 'img/logo/mobile.png'
favicon:  ''

vendor:
  name:
  url:

html_directionality:  'rtl' # ltl ( default ) "rtl", ltl
# Build settings
plugins:
  - jekyll-feed
  - jekyll-paginate

permalink: /blog/:title:output_ext
paginate: 6
paginate_path: "/blog/page:num/"


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

comments:
  provider               : 'disqus' # false (default), "disqus", "discourse", "facebook", "staticman", "staticman_v2", "utterances", "custom"
  disqus:
    shortname            : 'patrick-ducor' # https://help.disqus.com/customer/portal/articles/466208-what-s-a-shortname-
  discourse:
    server               : # https://meta.discourse.org/t/embedding-discourse-comments-via-javascript/31963 , e.g.: meta.discourse.org
  facebook:
    # https://developers.facebook.com/docs/plugins/comments
    appid                :
    num_posts            : # 5 (default)
    colorscheme          : # "light" (default), "dark"
  utterances:
    theme                : # "github-light" (default), "github-dark"
    issue_term           : # "pathname" (default)
  staticman:
    branch               : # "master"
    endpoint             : # "https://{your Staticman v3 API}/v3/entry/github/"

# Analytics
analytics:
  provider               : false # false (default), "google", "google-universal", "google-gtag", "custom"
  google:
    tracking_id          :
    anonymize_ip         : # true, false (default)

# google map key
google_map_key           : 'AIzaSyDz2w7HUaWudHwd7AWQpCL48Qs050WOn9s' # false (default),

# HTML Compression
# - https://jch.penibelst.de/
compress_html:
  clippings: all
  ignore:
    envs: development

##
getform_id: # to go https://getform.io/ and create an account for contact form


##########################################################################
################# seo ####################################################
##########################################################################
# SEO Related
google_site_verification :
bing_site_verification   :
yandex_site_verification :
naver_site_verification  :
og_image                 : '/images/profile.jpg' # Open Graph/Twitter default site image
header:
  - image                 : '/images/profile.jpg'

###########################################################################
###########################   Home / hero  ################################
###########################################################################

first_name: Sean's
last_name: Last Ride
cv_download_link: 'https://venmo.com/u/seank_23'
user_intro: '[Amidst the wild expanse, Sean, a cowboy silhouette against the rugged backdrop, channels the reflective vibe of Matthew McConaughey.]
Sean: Ava, shes like that aged cheese from the heart of Wisconsin, ya know? Layers of depth, complexities, and a flavor that lingers, much like the stories of the range. She aint just my partner; shes the taste of exploration woven into every adventure we saddle up for.
[Taking a moment to soak in the endless vista, he continues.]
Sean: Avas like a wheel of fine cheese, Patagonias skies—each moment with her, an unwrapping of new flavors, a richness akin to the untouched wilderness.
[Lost in reverie, a smile grazes Seans face.]
Sean: Being with her is like savoring the most exquisite Brie. Every trail ridden, every whispered dream shared, its a taste that lingers, leaving me craving more of this remarkable journey.
[Gazing out at the untamed terrain, a wistful air envelops Sean.]
Sean: Avas more than my travel partner; shes my blend of adventure and comfort, just like a fine cheese board under the stars. Shes... shes like the horizon I ride towards, a mix of adventure and familiarity etched into the map of our exploration.
[As the camera captures the raw beauty of the landscape, Sean remains, encapsulated in the essence of Ava, a cherished memory amidst the grandeur]
'


freelance_hire: true
professions:
  - Hooper
  - Machine Learning Engineer
  - Client Consultant
author_description: "<strong>Hello, I’m a Patrick</strong>, Data Scientist based on Kansas City. <br> I have rich experience in web site design &amp; building <br> and customization. Also I am good at <strong>html, css, <br> wordpress, php, jquery, bootstrap.</strong>"
social_link:
  - name: r-project
    icon: "FontAwesome5Brands-r-project"
    link: "https://rpubs.com/jjomalley94"
  - name: linkedin
    icon: "FontAwesome5Brands-linkedin"
    link: "https://www.linkedin.com/in/joseph-o-malley-9970a077/"
  - name: github
    icon: "FontAwesome5Brands-github"
    link: "https://github.com/ultrajoseph/JosephOMalley_code_portfolio"

##################################################################
################  professional_skills ############################
##################################################################
professional_skill_title: 'Skillz'
professional_skill_description: 'I think of myself as a weapon - legal in only 14 States'

professional_skills:
  - name: 'Beaning Slynes with a Pitch'
    percentage: '80'

  - name: 'Paying for Middle Aged Ladies Dinner in Europe'
    percentage: '90'

  - name: 'BAD BAD MAN 1st round draft pick'
    percentage: '100'

  - name: 'Turning into Giannis in a church league'
    percentage: '34'

##########################################
################ portfolios ##############
#########################################
portfolio_title: 'Filmography'
portfolio_tagline: 'Man of Many Talents'
portfolio_categories:

portfolios:
  - main_image: 'img/portfolio/sk_dr_evil.jpg'
    title: 'Mini Me'
    type:
    category:
    video_link:

  - main_image: 'img/portfolio/sk_mccon.jpg'
    title: 'Alright Alright Alright'
    type:
    category:
    video_link:

  - main_image: 'img/portfolio/sk_snap.jpg'
    title: 'At his best'
    type:
    category:
    video_link:

  - main_image: 'img/portfolio/sk_sodexo.jpg'
    title: 'Cashing checks'
    type:
    category:
    video_link:


############################################
############## testimonial #################
############################################
testimonials:
  - quote: 'Have never met a guy with lower self preservation. From a tent camp in Lousiville Ky to a hardwood floor in Madison... he may have been homeless in a past life'
    author_name: 'J-Rarri'
    author_image: '/img/about/jo_test.jpg'
    author_profession: 'Stay At Home Dad'
